package ds13.http

object HTTPClientConsts {

  val ERR_CODE_CLIENT_PROTOCOL_EXCEPTION = 0

  val ERR_CODE_IO_EXCEPTION = ERR_CODE_CLIENT_PROTOCOL_EXCEPTION + 1

  val ERR_CODE_NOT_EXPECTED = ERR_CODE_IO_EXCEPTION + 1

}